In [15]:
import numpy as np
import time

# Define the matrix
A = np.array([[2, 1],
              [1, 0]])

# Measure time taken for SVD computation
start_time = time.time()

# Compute the Singular Value Decomposition
U, S, VT = np.linalg.svd(A)

# Calculate elapsed time
svd_time = time.time() - start_time

# Print the matrices
print("Matrix U (Left singular vectors):")
print(U)
print("\nSingular values (Diagonal of Sigma):")
print(np.diag(S))
print("\nMatrix VT (Transpose of right singular vectors):")
print(VT)

# Reconstruct the original matrix using SVD
reconstructed_A = np.dot(U, np.dot(np.diag(S), VT))

# Check if the original matrix and reconstructed matrix are close
is_close = np.allclose(A, reconstructed_A)

# Print time taken for SVD computation
print("\nTime taken for SVD computation: {:.6f} seconds".format(svd_time))

# Print the correctness of the decomposition
if is_close:
    print("The decomposition is correct.")
else:
    print("The decomposition is not correct.")


Matrix U (Left singular vectors):
[[-0.92387953 -0.38268343]
 [-0.38268343  0.92387953]]

Singular values (Diagonal of Sigma):
[[2.41421356 0.        ]
 [0.         0.41421356]]

Matrix VT (Transpose of right singular vectors):
[[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]

Time taken for SVD computation: 0.001102 seconds
The decomposition is correct.


In [14]:
import numpy as np
import time

# Define the matrix
A = np.array([[2, 1],
              [1, 0],
              [0, 1]])

# Measure time taken for SVD computation
start_time = time.time()

# Compute the Singular Value Decomposition
U, S, VT = np.linalg.svd(A)

# Add a row of zeros to S
S_extended = np.vstack([np.diag(S), [0, 0]])

# Calculate elapsed time
svd_time = time.time() - start_time

# Print the matrices
print("Matrix U (Left singular vectors):")
print(U)
print("\nSingular values (Diagonal of Sigma):")
print(S_extended)
print("\nMatrix VT (Transpose of right singular vectors):")
print(VT)

# Reconstruct the original matrix using SVD
reconstructed_A = np.dot(U, np.dot(S_extended, VT))

# Check if the original matrix and reconstructed matrix are close
is_close = np.allclose(A, reconstructed_A)

# Print time taken for SVD computation
print("\nTime taken for SVD computation: {:.6f} seconds".format(svd_time))

# Print the correctness of the decomposition
if is_close:
    print("The decomposition is correct.")
else:
    print("The decomposition is not correct.")


Matrix U (Left singular vectors):
[[-9.12870929e-01  4.80183453e-17 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01  8.16496581e-01]
 [-1.82574186e-01  8.94427191e-01  4.08248290e-01]]

Singular values (Diagonal of Sigma):
[[2.44948974 0.        ]
 [0.         1.        ]
 [0.         0.        ]]

Matrix VT (Transpose of right singular vectors):
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]

Time taken for SVD computation: 0.000456 seconds
The decomposition is correct.


In [8]:
import numpy as np
import time

# Define the matrix
A = np.array([[2, 1],
              [-1, 1],
              [1, 1],
              [2, -1]])

# Measure time taken for SVD computation
start_time = time.time()

# Compute the Singular Value Decomposition
U, S, VT = np.linalg.svd(A)

# Adjust the shape of S to be 4x2 with zeros in additional rows
S_extended = np.zeros_like(A, dtype=float)
S_extended[:S.shape[0], :S.shape[0]] = np.diag(S)

# Calculate elapsed time
svd_time = time.time() - start_time

# Print the matrices
print("Matrix U (Left singular vectors):")
print(U)
print("\nSingular values (Diagonal of Sigma):")
print(S_extended)
print("\nMatrix VT (Transpose of right singular vectors):")
print(VT)

# Reconstruct the original matrix using SVD and extended S
reconstructed_A = np.dot(U, np.dot(S_extended, VT))

# Check if the original matrix and reconstructed matrix are close
is_close = np.allclose(A, reconstructed_A)

# Print time taken for SVD computation
print("\nTime taken for SVD computation: {:.6f} seconds".format(svd_time))

# Print the correctness of the decomposition
if is_close:
    print("The decomposition is correct.")
else:
    print("The decomposition is not correct.")



Matrix U (Left singular vectors):
[[-0.63245553 -0.5        -0.52229321 -0.27786652]
 [ 0.31622777 -0.5        -0.30196857  0.74753928]
 [-0.31622777 -0.5         0.79704714  0.12130893]
 [-0.63245553  0.5        -0.02721464  0.59098169]]

Singular values (Diagonal of Sigma):
[[3.16227766 0.        ]
 [0.         2.        ]
 [0.         0.        ]
 [0.         0.        ]]

Matrix VT (Transpose of right singular vectors):
[[-1. -0.]
 [-0. -1.]]

Time taken for SVD computation: 0.000517 seconds
The decomposition is correct.


In [9]:
import numpy as np
import time

# Define the matrix
A = np.array([[1, 1, 0],
              [-1, 0, 1],
              [0, 1, -1],
              [1, 1, -1]])

# Measure time taken for SVD computation
start_time = time.time()

# Compute the Singular Value Decomposition
U, S, VT = np.linalg.svd(A)

# Adjust the shape of S to be 4x3 with zeros in additional rows
S_extended = np.zeros_like(A, dtype=float)
S_extended[:S.shape[0], :S.shape[0]] = np.diag(S)

# Calculate elapsed time
svd_time = time.time() - start_time

# Print the matrices
print("Matrix U (Left singular vectors):")
print(U)
print("\nSingular values (Diagonal of Sigma):")
print(S_extended)
print("\nMatrix VT (Transpose of right singular vectors):")
print(VT)

# Reconstruct the original matrix using SVD and extended S
reconstructed_A = np.dot(U, np.dot(S_extended, VT))

# Check if the original matrix and reconstructed matrix are close
is_close = np.allclose(A, reconstructed_A)

# Print time taken for SVD computation
print("\nTime taken for SVD computation: {:.6f} seconds".format(svd_time))

# Print the correctness of the decomposition
if is_close:
    print("The decomposition is correct.")
else:
    print("The decomposition is not correct.")



Matrix U (Left singular vectors):
[[-4.36435780e-01  7.07106781e-01  4.08248290e-01 -3.77964473e-01]
 [ 4.36435780e-01  7.07106781e-01 -4.08248290e-01  3.77964473e-01]
 [-4.36435780e-01  3.33066907e-16 -8.16496581e-01 -3.77964473e-01]
 [-6.54653671e-01  3.33066907e-16 -5.55111512e-17  7.55928946e-01]]

Singular values (Diagonal of Sigma):
[[2.64575131 0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]]

Matrix VT (Transpose of right singular vectors):
[[-0.57735027 -0.57735027  0.57735027]
 [ 0.          0.70710678  0.70710678]
 [ 0.81649658 -0.40824829  0.40824829]]

Time taken for SVD computation: 0.000430 seconds
The decomposition is correct.


In [12]:
import numpy as np
import time

# Define the matrix
A = np.array([[0, 1, 1],
              [0, 1, 0],
              [1, 1, 0],
              [0, 1, 0],
              [1, 0, 1]])

# Measure time taken for SVD computation
start_time = time.time()

# Compute the Singular Value Decomposition
U, S, VT = np.linalg.svd(A)

# Adjust the shape of S to be 5x3 with zeros in additional rows
S_extended = np.zeros((A.shape[0], A.shape[1]))

# Fill in the diagonal elements of S with the singular values
S_extended[:S.shape[0], :S.shape[0]] = np.diag(S)

# Calculate elapsed time
svd_time = time.time() - start_time

# Print the matrices
print("Matrix U (Left singular vectors):")
print(U)
print("\nSingular values (Diagonal of Sigma):")
print(S_extended)
print("\nMatrix VT (Transpose of right singular vectors):")
print(VT)

# Reconstruct the original matrix using SVD and extended S
reconstructed_A = np.dot(U, np.dot(S_extended, VT))

# Check if the original matrix and reconstructed matrix are close
is_close = np.allclose(A, reconstructed_A)

# Print time taken for SVD computation
print("\nTime taken for SVD computation: {:.6f} seconds".format(svd_time))

# Print the correctness of the decomposition
if is_close:
    print("The decomposition is correct.")
else:
    print("The decomposition is not correct.")

Matrix U (Left singular vectors):
[[-5.47722558e-01  3.50476164e-16  7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01  4.08248290e-01 -1.48383873e-16 -5.43516408e-01
   6.36073827e-01]
 [-5.47722558e-01 -7.02388902e-17 -7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01  4.08248290e-01 -1.71841615e-16  8.07633333e-01
   2.18468301e-01]
 [-3.65148372e-01 -8.16496581e-01  2.43277252e-16  1.32058463e-01
   4.27271064e-01]]

Singular values (Diagonal of Sigma):
[[2.23606798 0.         0.        ]
 [0.         1.41421356 0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]

Matrix VT (Transpose of right singular vectors):
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-5.77350269e-01  5.77350269e-01 -5.77350269e-01]
 [-7.07106781e-01 -3.88578059e-16  7.07106781e-01]]

Time taken for SVD computation: 0.001100 seconds
The decomposition is correct.
